version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Zilch$$**2023
      - POSTGRES_USER=zilch_cards_user
      - POSTGRES_DB=zilch_cards_db
    restart: unless-stopped
  zilchcardsapp:
    image: zilchcards.jar:latest
    network_mode: bridge
    container_name: zilchcardsapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres