package com.zilch.payments;

public interface TestFixture {

  String SECRET_KEY = "vbL4Xt95jlpONhdSK1wGiguHRpqWeJjzaewmnaC74lrXEwiT";

  String VALID_AUTHORIZATION_TOKEN_WITH_FUTURE_EXP_DATE =
      "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX1VTRVIiLCJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sInN1YiI6InppbGNodGVzdHVzZXIiLCJpYXQiOjE2OTA3NTQ4NTYsImV4cCI6NjI0ODI3NTIwMDB9.AAIR7H60Z34H61avZrKDAnDbhguuvNuFTJ5-Q6mUYJY";

  String EXPIRED_AUTHORIZATION_TOKEN =
      "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IltTVEFOREFSRF9VU0VSXSIsInN1YiI6InppbGNodXNlciIsImlhdCI6MTY5MDI4NjUxNSwiZXhwIjoxNjkwMjg2NTE1fQ.J_a7KzMqm5lybjfGbktlkHL6AsQhTgCIoNEzkGkOoUk";

  String INVALID_AUTHORIZATION_TOKEN =
      "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IltTVEFOREFSRF9VU0VSXSIsInB1YiI6InppbGNodXNlciIsDrthdCI6MTY5MDI0MDk4NCwiZXhwIjoyNjM3NjE1MzgyfQ.rqd6Es7aiWdaCvp4EnQJw5TClE9Z4ACAWPfa_MLHRHY";

  String ZILCH_TEST_USER_NAME = "zilchtestuser";

  String ZILCH_TEST_USER_PASSWORD = "ZilchTest@1234";

  long ZILCH_TEST_USER_ID = 1;

  int ROLE_ID = 1;

  String ROLE_USER = "ROLE_USER";

  String USER_ROLES = "roles";
}
